# Generated by Django 3.2.8 on 2022-06-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_mail_mail_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='mail_co2e',
            field=models.FloatField(default=4.0),
        ),
    ]
